### PR TITLE
py4cl2 backport with minimal changes

### PR DESCRIPTION
**Pull request by digikar99**
Amongst the changes I'm aware of, one remains is that of numpy arrays using numpy-file-format, and generators. I can make it later this week.

I think the following changes merit a new major version, since it can literally break user code:
- changes to import-module and import-function, to defpymodule and defpyfun, importing arguments, lispifying names
- changes to chain, chain*
- changing remote-object to with-remote-object, if semantics deem appropriate

IMO, this PR is much cleaner. That went all over the place. :)

Also, [dzecniv suggested an idea of gentle deprecation for change of names](https://www.reddit.com/r/lisp/comments/cyf6k9/improving_upon_py4cl/eyvsse6?utm_source=share&utm_medium=web2x)

### CODE REVIEW

**Comment by bendudson** [comment]
Thanks! Breaking it up like this makes reviewing the changes much easier (as does having the tests pass :) ). Yes, I agree that keeping both names, and deprecating is a good way forward.

There are I think three kinds of breaking changes which can be worked around:
1. Changes which break compatibility with python 2. The clock is ticking (https://pythonclock.org/) but some people have to use it
2. Renaming symbols
3. Changes to the function/macro behaviour e.g. some of the changes to `chain`. I think ideally the function names should be different if they behave differently, so users have to think a bit about changing it.

Sorry if this seems overly complicated, but perhaps we can try:
1. Merging in changes which don't break anything (if there are any)
2. Tag as version 1
3. Merge in changes (1) and (2) which break compatibility with python 2. Old symbols print deprecation warnings but still work.
4. Tag as version 1.1
5. Merge in remaining changes

Would that be possible? Sorry it's a bit of work to split up things. Happy to help if we can find a way to divide up the work. Thanks again!

**Comment by digikar99** [comment]
Yup, that seems good. On breaking compatibility, I think [the first commit](https://github.com/bendudson/py4cl/pull/22/commits/1c8f2fc21bb7de1a48f7b19d181b8fdb9e2c1b75) is something that does break compatibility - if someone has used `(with-output-to-string (*standard-output*) ...)`. So, I think that is something that should be reverted.

**Comment by digikar99** [comment]
7f5259e on [my branch](https://github.com/digikar99/py4cl2/commits/py4cl2-backport) shows its failing the tests; while its passing here, and on my device. Any possible reasons?

**Comment by digikar99** [comment]
99820a0 Here, too, I am not sure what is wrong - the tests are passing on my device.

**Comment by bendudson** [comment]
I'll have a look asap and try to reproduce here. Probably be late today or sometime over the weekend.

**Comment by bendudson** [comment]
SBCL seems to be fine, but CCL failing...

**Comment by digikar99** [comment]
> SBCL seems to be fine, but CCL failing...

I'm unable to reproduce even after a clean clone. 

9f9a117 is with reference to:

> Yup, that seems good. On breaking compatibility, I think [the first commit](https://github.com/bendudson/py4cl/pull/22/commits/1c8f2fc21bb7de1a48f7b19d181b8fdb9e2c1b75) is something that does break compatibility - if someone has used `(with-output-to-string (*standard-output*) ...)`. So, I think that is something that should be reverted.

**Comment by digikar99** [comment]
> SBCL seems to be fine, but CCL failing...

I'm unable to reproduce even after a clean clone. 

9f9a117 is with reference to:

> Yup, that seems good. On breaking compatibility, I think [the first commit](https://github.com/bendudson/py4cl/pull/22/commits/1c8f2fc21bb7de1a48f7b19d181b8fdb9e2c1b75) is something that does break compatibility - if someone has used `(with-output-to-string (*standard-output*) ...)`. So, I think that is something that should be reverted.

**Comment by digikar99** [comment]
I think those are all the changes possible without breaking backward compatibility. 

(Let me know if I missed out anything.)

**Comment by bendudson** [comment]
Thanks very much! Sorry for the long delay, many things going on currently.

**Comment by digikar99** [comment]
> Thanks very much! Sorry for the long delay, many things going on currently.

Ah, that's alright; everyone can be busy at times.

**Pull request merged**
